language: ruby
rvm:
- 2.3.1
env:
  matrix:
  - DB=sqlite
  global:
  - secure: sK13sAlb0VY3KF1cU8Vi97EQPbWzqXJh6lj3IE1N3cOFa0O32Uzyn+MF2Ptp9V6JfW3uE79FTqdecbGgM8pEaiVCCXrXMaxBioFsQVORf+TLG2JqHm1zqCwt3WB9ZXMMFWLfRvJmVKOowPURgDPpuW+lvPdpEoZ2gAMb7HACrgQg4UfL4YFBQfuPTEOuhpSUN2fxqHFLuN4CQnWM1vr2qEKABi0tkPbVTpPsb2nwkIVEW90QQ87ZL7M9RjNpVkETyHgdWMWI8hQcQKmAlhTsnoOsTuaGlqa6cZXgJvvl+OiBWBzeTHg3r7sZYkBarhI60I1EdWBhE8rZoVO6s4cqryh4lt85FYh8ZJdHK545y0l1pG5uecpCAzcOFlEV5Fr4wPxWt1jzqnbVYFjEKuSmHTs6W+fH9f4dve63MrV0O4bULKYL3uIm07ppHMJ0DI7l/dv+WDKjFyL77e9lkxVj1iWkbSTYoqJ3T2yrfzz1B9hit/Cg49sSXLrig3CcMGMdkcbPUIE08ZwUIaELRKlThJiPtM2aiEJIdJOxKA6Jwrl7x2m5sS6hPNRI6KEhzBdyLy2NsfGy8541njCBwHTr3cP962d+tvbdOW8kslpyifU8luQLZqE8WXaapaiiAfcnDMVkMmMOY9KUpnns4YT7reDnzaRRL7HqWwu6xGcWzUA=
  - secure: spwgqjsoFMSaqcmrOQqXVPQLPUiEChll25d0SCESrun3Nvo/ukfURfq+OSnGNUMixaWKexhcMqMdx99nehIMIQPhjsgK7e6zDVoknLC3zp9zDi+SUzwwt4IQQSSdL3cTnMfB/O817V/jVvnZoGicvzVtVdG4vq18kSzTcMdZ+RHwOsVCcULv1MacI7IrKzhFK7FBLtb4l2LuH9slV9lWDSOyrutueTL1W7s3/ZfFQLj0Zgz8+POTGgzo2DyRQmym9omBJTfNCt+AHiz+ikAfnBy+3GMJca1AYD8LCBRqQDCvx+daEKEqzMNsiXGOJrLw6IzLNMF9NCXwWsTwQZJqHBTPOi7V7SJ6uo+D4lUYwz1Zds6NDqjfYiQ/J2ucmWRYcuddePhT5+CJA+y4KLBIzZ42i3a32c+SbauUQ68T5KUU8b3cEhr7EsZn8VsnGZuTh18q81X2zwxc1q4l6puvs7qRnVPOxW1E6dGKE5+wbFzxjkZ3i9EUseiwMDsSZuWU8SYAWP5FmqUkzb4s38ym3tF1yK95MmARlvDfP810GPda1DkOGhtGauQchLPvpEEYyJBblwLPCtlh2ZiQvo4BqKJx3h9XoHtAnsViO200EHpnU9Rf4ldXViyDG+vxmXRTuvIAwq33LO3qmPWuIO5uomo3hQS2zpsZUncOqNfZgck=
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
- xvfb-run rspec
before_script:
- cp config/database.travis.yml config/database.yml
